routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['locale'])->group(function () {
    Route::get('/offer/{job_offer}', 'Admin\JobOfferController@show')->name('offer.show');
    Route::get('/employer/{employer_details}', 'Admin\SettingsController@show');

    Route::namespace('Client')->group(function () {
        Route::get('/', 'ClientController@index');
        Route::get('/search', 'SearchController@searchJobOffers');
        Route::get('/search/cv', 'SearchController@searchEmployees')->middleware('auth', 'admin');
        Route::get('/cv/{id}', 'CurriculumVitaeController@show')->middleware('auth', 'admin');

        Route::middleware(['auth', 'verified', 'client'])->group(function () {
            //    CV
            Route::get('/cv', 'CurriculumVitaeController@index')->name('cv.index');
            Route::post('/cv', 'CurriculumVitaeController@store')->name('cv.store');
        });
    });

    //api
    Route::namespace('Api')->prefix('api')->group(function () {
        Route::get('/job-offers', 'JobOfferController@index');
        Route::get('/places/provinces', 'PlaceController@getProvinces');
        Route::get('/places/communities/{province}', 'PlaceController@getCommunities');

        Route::middleware(['auth'])->group(function () {
            Route::post('/job-offer/apply/{job_offer}', 'JobOfferController@applyToOffer');
            Route::get('/places/{getBy?}/{id?}', 'PlaceController@index');
        });
    });

    Auth::routes(['verify' => true]);
});

Route::namespace('Admin')->middleware(['auth', 'admin'])->group(function () {
    Route::get('/questionary', 'SettingsController@showQuestionary');

    Route::prefix('admin')->middleware(['verified'])->group(function () {
        Route::get('details', 'DetailsController');
        Route::post('settings', 'SettingsController@store')->name('settings.store');

        Route::middleware(['details'])->group(function () {
            Route::get('/', 'DashboardController@index')->name('admin.index');

            //    settings
            Route::put('settings', 'SettingsController@update')->name('settings.update');
            Route::get('settings', 'SettingsController@index')->name('settings.index');

//        job offers
            Route::get('job-offers/archive', 'JobOfferController@archive')->name('job-offers.archive');
            Route::patch('job-offers/{job_offer}/restore', 'JobOfferController@restore')->name('job-offers.restore');

            Route::resources([
                'job-offers' => 'JobOfferController'
            ]);
        });
    });
});



Route::get('/locale/{locale}', function ($locale) {
    session(['locale' => $locale]);
    return back();
})->name('locale');

app/Models/CurriculumVitae.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CurriculumVitae extends Model
{
    protected $guarded = ['id', 'user_id'];
    protected $casts = [
        'phone' => 'array',
        'education_details' => 'array',
        'languages' => 'array',
        'military_book' => 'boolean',
        'drive_right' => 'boolean'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function experiences()
    {
        return $this->hasMany('App\Experience', 'cv_id');
    }

    public function getBirthDateAttribute($value)
    {
        return date(config('app.date_format'), strtotime($value));
    }

    public function setBirthDateAttribute($value)
    {
        $this->attributes['birth_date'] = date('Y-m-d', strtotime($value));
    }

    public function spheres()
    {
        return $this->belongsToMany('App\ActivitySphere')->withPivot(['experience']);
    }

    public function getAvatarAttribute($value)
    {

        return is_null($value) ? null : asset('storage/avatars/' . $value . '.png');
    }

    public function setMilitaryBookAttribute($value)
    {
        $this->attributes['military_book'] = boolval($value);
    }

    public function setDriveRightAttribute($value)
    {
        $this->attributes['drive_right'] = boolval($value);
    }

    public function community()
    {
        return $this->belongsTo('App\Community');
    }

    public function getLanguagesAsStringAttribute()
    {
        return implode(', ', array_map(function ($lang) {
            return __('options.languages.' . $lang);
        }, $this->languages));
    }
}

resources/views/pdf/cv.blade.php
<table border="1" style="border-collapse: collapse; font-size: 12px;" cellpadding="4" align="center" width="90%">
    <thead>
        <tr>
            @if($cv->avatar)
            <td>
                <img src="{{ $cv->avatar }}">
            </td>
            @endif
            <th @if(!$cv->avatar) colspan="2" @endif>
                <h3>{{ $cv->name }}</h3>
                <p><small>{{ $user->email }}</small></p>
                @if(!empty($cv->phone))
                    <p><small>
                            @foreach($cv->phone as $phone)
                                {{ $phone['phone'] . ' ' }}
                            @endforeach
                        </small></p>
                @endif
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>@lang('cv.birth_date')</th>
            <td>{{ $cv->birth_date }}</td>
        </tr>
        <tr>
            <th>@lang('cv.place')</th>
            <td>
                @if ($cv->community_id){{ $cv->community->region->province->name . ', ' . $cv->community->region->name . ', ' . $cv->community->name }} @if ($cv->address) <br> @endif @endif
                @if ($cv->address) {{ $cv->address }}@endif
            </td>
        </tr>
        <tr>
            <th>@lang('cv.education')</th>
            <td align="center">
                <p>
                    <strong>@lang('options.education.' . $cv->education)</strong>
                </p>
                <br>
                <table border="1" style="border-collapse: collapse" cellpadding="3" width="100%">
                    <thead>
                        <tr>
                            <th>@lang('cv.institution')</th>
                            <th>@lang('cv.profession')</th>
                            <th>@lang('cv.start_date')</th>
                            <th>@lang('cv.end_date')</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($cv->education_details as $edu)
                            <tr>
                                <td>{{ $edu['institution'] }}</td>
                                <td>{{ $edu['profession'] }}</td>
                                <td>{{ $edu['start_date'] }}</td>
                                <td>{{ $edu['end_date'] }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <th>@lang('cv.languages')</th>
            <td>
                {{ $cv->languagesAsString }}
            </td>
        </tr>
        <tr>
            <th>@lang('cv.desired_sphere') <small>(@lang('cv.sphere_experience'))</small></th>
            <td>
                <ul>
                    @foreach($cv->spheres as $sphere)
                    <li>{{ $sphere->title }} <small>({{ __('options.experiences.' . $sphere->pivot->experience) }})</small></li>
                    @endforeach
                </ul>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <p>
                    <strong>@lang('cv.experience')</strong>
                </p>
                <br>
                <table border="1" style="border-collapse: collapse" cellpadding="3" width="100%">
                    <thead>
                        <tr>
                            <th>@lang('cv.organization')</th>
                            <th>@lang('cv.sphere')</th>
                            <th>@lang('cv.position')</th>
                            <th>@lang('cv.start_date')</th>
                            <th>@lang('cv.end_date')</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($cv->experiences as $experience)
                            <tr>
                                <td>{{ $experience->organization }}</td>
                                <td>{{ $experience->sphere->title }}</td>
                                <td>{{ $experience->position }}</td>
                                <td>{{ $experience->start_date }}</td>
                                <td>{{ $experience->end_date }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <th>@lang('cv.skills')</th>
            <td>{!! $cv->skills !!}</td>
        </tr>
        <tr>
            <th>@lang('cv.military_book')</th>
            <td>
                <img src="{{ $cv->military_book ? asset('img/icon_check.png') : asset('img/icon_uncheck.png') }}" height="14">
            </td>
        </tr>
        <tr>
            <th>@lang('cv.drive_right')</th>
            <td>
                <img src="{{ $cv->drive_right ? asset('img/icon_check.png') : asset('img/icon_uncheck.png') }}" height="14">
            </td>
        </tr>
    </tbody>
</table>