routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['locale'])->group(function () {
    Route::get('/offer/{job_offer}', 'Admin\JobOfferController@show')->name('offer.show');
    Route::get('/employer/{employer_details}', 'Admin\SettingsController@show');

    Route::namespace('Client')->group(function () {
        Route::get('/', 'ClientController@index');
        Route::get('/search', 'SearchController@searchJobOffers');
        Route::get('/search/cv', 'SearchController@searchEmployees')->middleware('auth', 'admin');
        Route::get('/cv/{id}', 'CurriculumVitaeController@show')->middleware('auth', 'admin');

        Route::middleware(['auth', 'verified', 'client'])->group(function () {
            //    CV
            Route::get('/cv', 'CurriculumVitaeController@index')->name('cv.index');
            Route::post('/cv', 'CurriculumVitaeController@store')->name('cv.store');
        });
    });

    //api
    Route::namespace('Api')->prefix('api')->group(function () {
        Route::get('/job-offers', 'JobOfferController@index');
        Route::get('/places/provinces', 'PlaceController@getProvinces');
        Route::get('/places/communities/{province}', 'PlaceController@getCommunities');

        Route::middleware(['auth'])->group(function () {
            Route::post('/job-offer/apply/{job_offer}', 'JobOfferController@applyToOffer');
            Route::get('/places/{getBy?}/{id?}', 'PlaceController@index');
        });
    });

    Auth::routes(['verify' => true]);
});

Route::namespace('Admin')->middleware(['auth', 'admin'])->group(function () {
    Route::get('/questionary', 'SettingsController@showQuestionary');

    Route::prefix('admin')->middleware(['verified'])->group(function () {
        Route::get('details', 'DetailsController');
        Route::post('settings', 'SettingsController@store')->name('settings.store');

        Route::middleware(['details'])->group(function () {
            Route::get('/', 'DashboardController@index')->name('admin.index');

            //    settings
            Route::put('settings', 'SettingsController@update')->name('settings.update');
            Route::get('settings', 'SettingsController@index')->name('settings.index');

//        job offers
            Route::get('job-offers/archive', 'JobOfferController@archive')->name('job-offers.archive');
            Route::patch('job-offers/{job_offer}/restore', 'JobOfferController@restore')->name('job-offers.restore');

            Route::resources([
                'job-offers' => 'JobOfferController'
            ]);
        });
    });
});



Route::get('/locale/{locale}', function ($locale) {
    session(['locale' => $locale]);
    return back();
})->name('locale');

app/Models/JobOffer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class JobOffer extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $guarded = ['id', 'user_id'];

    protected $casts = [
        'languages' => 'array'
    ];

    protected $appends = ['location'];

    public function employer()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function activitySphere()
    {
        return $this->belongsTo('App\ActivitySphere');
    }

    public function community()
    {
        return $this->belongsTo('App\Community');
    }

    public function getLocationAttribute()
    {
        $location = '';
        $hasAddress = !is_null($this->address);

        if (!is_null($this->community_id)) {
            $location .= $this->community->region->province->name . ', ' . $this->community->region->name . ', ' . $this->community->name;

            if ($hasAddress) {
                $location .= ', ';
            }
        }

        if ($hasAddress) {
            $location .= $this->address;
        }

        return $location;
    }

    public function getOpeningDateAttribute($value)
    {
        if (is_null($value))
        {
            return $value;
        }

        return date(config('app.date_format'), strtotime($value));
    }

    public function setOpeningDateAttribute($value)
    {
        if (is_null($value)) {
            $this->attributes['opening_date'] = null;
        } else {
            $this->attributes['opening_date'] = date('Y-m-d', strtotime($value));
        }
    }
    public function getDeadlineAttribute($value)
    {
        if (is_null($value))
        {
            return $value;
        }

        return date(config('app.date_format'), strtotime($value));
    }

    public function setDeadlineAttribute($value)
    {
        if (is_null($value)) {
            $this->attributes['deadline'] = null;
        } else {
            $this->attributes['deadline'] = date('Y-m-d', strtotime($value));
        }
    }

    public function getUpdatedAtAttribute($value)
    {
        return date(config('app.date_format'), strtotime($value));
    }

    public function getCreatedAtAttribute($value)
    {
        return date(config('app.date_format'), strtotime($value));
    }

    public function getDeletedAtAttribute($value)
    {
        if (is_null($value))
        {
            return $value;
        }

        return date(config('app.date_format'), strtotime($value));
    }
}

app/Http/Controllers/Admin/JobOfferController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreJobOfferRequest;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\JobOffer;
use App\ActivitySphere;

class JobOfferController extends Controller
{
    private $jobOffer;
    private $activitySphere;

    public function __construct(JobOffer $jobOffer, ActivitySphere $activitySphere)
    {
        $this->authorizeResource(JobOffer::class, 'job_offer');

        $this->jobOffer = $jobOffer;
        $this->activitySphere = $activitySphere;
    }

    public function index(Request $request)
    {
        if($request->ajax()) {
            return $this->getJsonList($request);
        }

        return view('admin.job_offers.index', [
            'archiveCount' => $request->user()->jobOffers()->onlyTrashed()->count()
        ]);
    }

    public function create(Request $request)
    {
        $user = $request->user();

        return view('admin.job_offers.create', [
            'spheres' => $this->activitySphere->all(),
            'details' => $user->employerDetails()->first(['activity_sphere_id', 'community_id', 'address'])
        ]);
    }

    public function store(StoreJobOfferRequest $request)
    {
        $jobOffer = $this->jobOffer->fill($request->except(['_token']));
        $request->user()->jobOffers()->save($jobOffer);
        return redirect(route('job-offers.index'));
    }

    public function show(JobOffer $jobOffer)
    {
        $jobOffer->load([
            'employer' => function ($query) {
                $query->select(['users.id'])
                    ->with(['employerDetails' => function ($query) {
                        $query->select(['employer_details.id', 'employer_details.user_id', 'employer_details.name', 'employer_details.logo']);
                    }]);
            },
            'community' => function ($query) {
                $query->with(['region' => function ($query) {
                    $query->with(['province']);
                }]);
            },
            'activitySphere'
        ]);

        return view('client.job_offer.show', [
            'offer' => $jobOffer
        ]);
    }

    public function edit(JobOffer $jobOffer)
    {
        return view('admin.job_offers.edit',[
            'offer' => $jobOffer,
            'spheres' => $this->activitySphere->all()
        ]);
    }

    public function update(StoreJobOfferRequest $request, JobOffer $jobOffer)
    {
        $update = $request->except(['_token', '_method']);
        $update['community_id'] = $request->input('community_id', null);

        $jobOffer->fill($update);
        $jobOffer->save();
        return redirect(route('job-offers.index'));
    }

    public function destroy(JobOffer $jobOffer)
    {
        $jobOffer->delete();
    }

    public function archive(Request $request)
    {
        if ($request->ajax()) {
            return $this->getJsonArchiveList($request);
        }

        return view('admin.job_offers.archive');
    }

    public function restore($id)
    {
        $jobOffer = $this->jobOffer->withTrashed()->find($id);
        $restored = $jobOffer->replicate();
        $restored->deleted_at = null;
        $restored->save();

        return $restored->id;
    }

    private function getJsonList($request)
    {
        $recordsTotal = $recordsFiltered = 0;
        $search = $request->input('search')['value'];

        $data = $request->user()->jobOffers()
            ->tap(function ($query) use (&$recordsTotal, &$recordsFiltered) {
                $recordsTotal = $recordsFiltered = $query->count();
            })
            ->when($search, function ($query) use ($search, &$recordsFiltered) {
                $query->where('title', 'LIKE', '%'. $search .'%');
                $recordsFiltered = $query->count();
            })
            ->skip($request->input('start'))
            ->take($request->input('length'))
            ->orderBy($request->input('columns')[$request->input('order')[0]['column']]['name'], $request->input('order')[0]['dir'])
            ->get(['id', 'title', 'opening_date', 'deadline', 'updated_at']);


        return [
            'draw' => (int)$request->draw,
            'recordsTotal' => $recordsTotal,
            'recordsFiltered' => $recordsFiltered,
            'data' => $data
        ];
    }

    private function getJsonArchiveList($request)
    {
        $recordsTotal = $recordsFiltered = 0;
        $search = $request->input('search')['value'];

        $data = $request->user()->jobOffers()
            ->onlyTrashed()
            ->tap(function ($query) use (&$recordsTotal, &$recordsFiltered) {
                $recordsTotal = $recordsFiltered = $query->count();
            })
            ->when($search, function ($query) use ($search, &$recordsFiltered) {
                $query->where('title', 'LIKE', '%'. $search .'%');
                $recordsFiltered = $query->count();
            })
            ->skip($request->input('start'))
            ->take($request->input('length'))
            ->orderBy($request->input('columns')[$request->input('order')[0]['column']]['name'], $request->input('order')[0]['dir'])
            ->get(['id', 'title', 'opening_date', 'deadline', 'deleted_at']);


        return [
            'draw' => (int)$request->draw,
            'recordsTotal' => $recordsTotal,
            'recordsFiltered' => $recordsFiltered,
            'data' => $data
        ];
    }
}

app/Http/Controllers/Api/JobOfferController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendApplication;
use App\JobOffer;

class JobOfferController extends Controller
{
    private $jobOffer;

    public function __construct(JobOffer $jobOffer)
    {
        $this->jobOffer = $jobOffer;
    }

    public function index(Request $request)
    {
        return [
            'offers' => $this->jobOffer
                ->when($request->has('employer'), function ($query) use ($request) {
                    $query->where('job_offers.user_id', $request->get('employer'));
                })
                ->when($request->has('kwd'), function ($query) use ($request) {
                    $query->where('job_offers.title', 'like', '%' . $request->get('kwd') . '%');
                })
                ->where(function ($query) use ($request) {
                    if ($request->has('othercountry')) {
                        $query->whereNull('community_id');
                    } else {
                        if ($request->has('community') && $request->get('community') !== '0') {
                            $query->where('community_id', $request->get('community'))->whereNotNull('community_id');
                        } elseif ($request->has('province') && $request->get('province') !== '0') {
                            $query->whereHas('community', function ($community) use ($request) {
                                $community->whereHas('region', function ($region) use ($request) {
                                    $region->whereHas('province', function ($province) use ($request) {
                                        $province->where('id', $request->get('province'));
                                    });
                                });
                            });
                        }
                    }
                })
                ->when($request->has('sphere') && $request->get('sphere') !== 'na', function ($query) use ($request) {
                    $query->where('job_offers.activity_sphere_id', $request->get('sphere'));
                })
                ->when($request->has('education') && $request->get('education') !== 'na', function ($query) use ($request) {
                    $query->where('job_offers.education', $request->get('education'));
                })
                ->when($request->has('experience') && $request->get('experience') !== 'na', function ($query) use ($request) {
                    $query->where('job_offers.experience', $request->get('experience'));
                })
                ->with([
                    'employer' => function ($query) {
                        $query->select(['id'])
                            ->with(['employerDetails' => function ($query) {
                                $query->select(['employer_details.id', 'employer_details.user_id', 'employer_details.name', 'employer_details.logo']);
                            }]);
                    },
                    'community' => function ($query) {
                        $query->with(['region' => function ($query) {
                            $query->with(['province']);
                        }]);
                    },
                    'activitySphere'
                ])
                ->orderBy('id', 'desc')
                ->get()
        ];
    }

    public function applyToOffer($jobOffer, Request $request)
    {
        $jobOffer = $this->jobOffer->findOrFail($jobOffer);
        $jobOffer->load(['employer' => function ($query) {
            $query->select(['users.id'])
                ->with(['employerDetails' => function ($query) {
                    $query->select(['employer_details.user_id', 'employer_details.email']);
                }]);
        }]);

        Mail::to($jobOffer->employer->employerDetails->email)->locale(session('locale'))->send(new SendApplication($jobOffer, $request->user(), $request->get('motivation')));

        return back()->with(['applicationSent' => true]);
    }
}

resources/views/admin/job_offers/archive.blade.php
@extends('layouts.admin')
@push('styles')
    <link rel="stylesheet" href="{{ asset('theme/vendor/DataTables-1.10.18/datatables.min.css') }}">
@endpush
@section('content')
    @breadcrumb(['data' => [
    ['հայտարարություններ', route('job-offers.index')],
    'արխիվ'
    ]])
    <div class="card">
        <div class="card-body">
            <table class="table table-hover w-100" id="jobOfferArchiveList">
                <thead>
                <tr>
                    <th>Անվանում</th>
                    <th>@lang('offer.opening_date')</th>
                    <th>@lang('offer.deadline')</th>
                    <th>Արխիվացվել է</th>
                    <td class="text-center">
                        <i class="fa fa-cogs"></i>
                    </td>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
@endsection
@push('scripts')
    <script src="{{ asset('theme/vendor/DataTables-1.10.18/datatables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/datatables.settings.js') }}"></script>
    <script src="{{ asset('js/datatables/jobOfferArchiveList.init.js') }}"></script>
@endpush

resources/views/admin/job_offers/create.blade.php
@extends('layouts.admin')
@push('styles')
    <link rel="stylesheet" href="{{ asset('theme/vendor/bootstrap-datepicker/bootstrap-datepicker3.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/bs-stepper.css') }}" media="all">
@endpush
@section('content')
    @breadcrumb(['data' => [
        ['հայտարարություններ', route('job-offers.index')],
        'ստեղծել հայտարարություն'
    ]])

    <div class="card">
        <div class="card-body">
            <div data-provider="stepper" class="bs-stepper">
                <div class="bs-stepper-header">
                    <div class="step" data-target="#description_step">
                        <a href="#">
                            <span class="bs-stepper-circle">1</span>
                            <span class="bs-stepper-label">Նկարագրություն</span>
                        </a>
                    </div>
                    <div class="line"></div>
                    <div class="step" data-target="#requirements_step">
                        <a href="#">
                            <span class="bs-stepper-circle">2</span>
                            <span class="bs-stepper-label">Պահանջներ</span>
                        </a>
                    </div>
                </div>
                <div class="bs-stepper-content">
                    <form action="{{ route('job-offers.store') }}" method="post">
                        @csrf
                        <div id="description_step" class="content">
                            <div class="form-group">
                                <label for="title" class="required">Անվանում</label>
                                <input
                                        type="text"
                                        class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}"
                                        id="title"
                                        name="title"
                                        value="{{ old('title') }}"
                                >
                            </div>
                            <div class="form-group">
                                <label for="sphere">Ոլորտ</label>
                                <select name="activity_sphere_id" id="sphere" class="form-control">
                                    @foreach ($spheres as $sphere)
                                        <option
                                                value="{{ $sphere->id }}"
                                                {{ old('activity_sphere_id') === (string)$sphere->id || $details->activity_sphere_id === $sphere->id ? 'selected' : '' }}
                                        >{{ $sphere->title }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="description">Նկարագրություն</label>
                                <textarea name="description" data-provider="tinymce" class="autoheight">{{old('description')}}</textarea>
                            </div>
                            <div class="form-group">
                                <label>@lang('offer.term')</label>
                                <div>
                                    @foreach (__('options.terms') as $key => $value)
                                        <div class="custom-control custom-radio custom-control-inline">
                                            <input
                                                    type="radio"
                                                    id="term_{{ $key }}"
                                                    name="term"
                                                    value="{{ $key }}"
                                                    class="custom-control-input"
                                                    {{ old('term') === (string)$key || $key === 0 ? 'checked' : '' }}
                                            >
                                            <label class="custom-control-label" for="term_{{ $key }}">{{ $value }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <div class="form-group">
                                <label>@lang('offer.type')</label>
                                <div>
                                    @foreach (__('options.types') as $key => $value)
                                        <div class="custom-control custom-radio custom-control-inline">
                                            <input
                                                    type="radio"
                                                    id="type_{{ $key }}"
                                                    name="type"
                                                    value="{{ $key }}"
                                                    class="custom-control-input"
                                                    {{ old('type') === (string)$key || $key === 0 ? 'checked' : '' }}
                                            >
                                            <label class="custom-control-label" for="type_{{ $key }}">{{ $value }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Վայրը</label>
                                <place-select old="{{ old('community_id') ?: $details->community_id }}" address="{{ old('address') ?: $details->address }}"></place-select>
                            </div>
                            <div class="form-group">
                                <label for="opening_date">@lang('offer.opening_date')</label>
                                <input
                                        type="text"
                                        class="form-control {{ $errors->has('opening_date') ? 'is-invalid' : '' }}"
                                        id="opening_date"
                                        name="opening_date"
                                        value="{{ old('opening_date') ?: date(config('app.date_format')) }}"
                                        data-provide="datepicker"
                                        autocomplete="off"
                                >
                            </div>
                            <div class="form-group">
                                <label for="deadline">@lang('offer.deadline')</label>
                                <input
                                        type="text"
                                        class="form-control {{ $errors->has('deadline') ? 'is-invalid' : '' }}"
                                        id="deadline"
                                        name="deadline"
                                        value="{{ old('deadline') ?: date(config('app.date_format')) }}"
                                        data-provide="datepicker"
                                        autocomplete="off"
                                >
                            </div>
                            <div class="text-right">
                                <button type="button" class="btn btn-primary" onclick="myStepper.next()">Հաջորդը</button>
                            </div>
                        </div>
                        <div id="requirements_step" class="content">
                            <div class="form-group">
                                <label>@lang('cv.education')</label>
                                <div>
                                    @foreach (__('options.education') as $key => $value)
                                        <div class="custom-control custom-radio custom-control-inline">
                                            <input type="radio"
                                                   id="education_{{ $key }}"
                                                   name="education"
                                                   value="{{ $key }}"
                                                   class="custom-control-input"
                                                   @if (old('education') === (string)$key || $key === 0) checked @endif
                                            >
                                            <label class="custom-control-label" for="education_{{ $key }}">{{ $value }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <div class="form-group">
                                <label>@lang('cv.experience')</label>
                                <div>
                                    @foreach (__('options.experiences') as $key => $value)
                                        <div class="custom-control custom-radio custom-control-inline">
                                            <input type="radio"
                                                   id="experience_{{ $key }}"
                                                   name="experience"
                                                   value="{{ $key }}"
                                                   class="custom-control-input"
                                                   @if (old('experience') === (string)$key || $key === 0) checked @endif
                                            >
                                            <label class="custom-control-label" for="experience_{{ $key }}">{{ $value }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                            <div class="form-group">
                                <label>@lang('cv.languages')</label>
                                <div>
                                    @foreach(__('options.languages') as $key => $lang)
                                        <div class="custom-control custom-checkbox custom-control-inline">
                                            <input type="checkbox"
                                                   class="custom-control-input"
                                                   name="languages[]"
                                                   id="languge_{{ $key }}"
                                                   value="{{ $key }}"
                                                   @if ((is_array(old('languages')) && in_array($key, old('languages'))) || (!is_array(old('languages')) && $key === 'hy'))
                                                       checked
                                                   @endif
                                            >
                                            <label class="custom-control-label" for="languge_{{ $key }}">{{ $lang }}</label>
                                        </div>
                                    @endforeach
                                </div>
                                <span class="form-text text-danger">{{ $errors->has('languages') ? 'Նվազագույնը մեկ լեզու' : '' }}</span>
                            </div>
                            <div class="form-group">
                                <label for="required_qualifications">@lang('cv.skills')</label>
                                <textarea name="skills" data-provider="tinymce" class="autoheight">{{old('skills')}}</textarea>
                            </div>
                            <div class="form-group">
                                <label>@lang('cv.military_book')</label>
                                <div>
                                    <button-switch options="{{ json_encode(__('options.military_book')) }}" name="military_book" checked="{{ old('military_book') }}"></button-switch>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>@lang('cv.drive_right')</label>
                                <div>
                                    <button-switch options="{{ json_encode(__('options.drive_right')) }}" name="drive_right" checked="{{ old('drive_right') }}"></button-switch>
                                </div>
                            </div>
                            <div class="text-right">
                                <button type="button" class="btn btn-primary" onclick="myStepper.previous()">Նախորդը</button>
                                <button type="submit" class="btn btn-success">Հաստատել</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <p class="text-right">@lang('cv.required_warning')</p>
        </div>
    </div>
@endsection
@push('scripts')
    <script src="{{ asset('theme/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('theme/vendor/bootstrap-datepicker/bootstrap-datepicker.hy.min.js') }}"></script>
    <script src="{{ asset('theme/vendor/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ asset('js/tinymce.init.js') }}"></script>
    <script src="{{ asset('js/stepper.init.js') }}"></script>
@endpush

resources/views/admin/job_offers/index.blade.php
@extends('layouts.admin')
@push('styles')
    <link rel="stylesheet" href="{{ asset('theme/vendor/DataTables-1.10.18/datatables.min.css') }}">
@endpush
@section('content')
    <div class="mb-2">
        <a href="{{ route('job-offers.create') }}" class="btn btn-primary">
            Ստեղծել հայտարարություն
        </a>
        <a href="{{ route('job-offers.archive') }}" class="btn btn-secondary">
            Արխիվ
            <span class="badge badge-light" id="archiveCounterBadge">{{ $archiveCount }}</span>
        </a>
    </div>
    <div class="card">
        <div class="card-body">
            <table class="table table-hover w-100" id="jobOfferList">
                <thead>
                    <tr>
                        <th>Անվանում</th>
                        <th>@lang('offer.opening_date')</th>
                        <th>@lang('offer.deadline')</th>
                        <th>Թարմացվել է</th>
                        <td class="text-center">
                            <i class="fa fa-cogs"></i>
                        </td>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
@endsection
@push('scripts')
    <script src="{{ asset('theme/vendor/DataTables-1.10.18/datatables.min.js') }}"></script>
    <script src="{{ asset('js/datatables/datatables.settings.js') }}"></script>
    <script src="{{ asset('js/datatables/jobOfferList.init.js') }}"></script>
@endpush